### ISSUE TITLE
Make the JSONdoc easy accessible

### ISSUE THREAD

**Issue by jGleitz** [HelfenKannJeder/come2help-server#13]
As far as I can see, the JSONdoc tool is pretty neat – especially the playground might prove really useful for frontend development.
Unfortunately, building the server package is quite complex and can hardly be automated (because of dependencies).

Ideally, you could specify a maven build that builds a JSONdoc jar. The jar could then be put on some server with continuous integration. In that way, the frontend team could always pull the most recent API for development. That would reduce the dependencies to only Java (ideally, Java 7 would work, too), which makes things easier.

Is that possible?

**Comment by MariusKl** [comment]
Good idea!

I just had a brief look at http://jsondoc.org/how-to-package-docs.html and it seems it is possible
"This is useful when you want to distribute your documentation to people that do not have access to the server hosting your API (and your JSONDoc endpoint)."

**Comment by jGleitz** [comment]
Yeah, that sounds perfect.

It's a plus that it will produce a zip, as you will not even need to have Java to play with the API.
