### ISSUE TITLE
Integrate backend and frontend on one server

### ISSUE THREAD

**Issue by MariusKl** [HelfenKannJeder/come2help-server#25]

**Comment by andreas-eberle** [comment]
@valentinz: I think this one is finished, isn't it? I can run both together on my machine. Maybe you can add the required configs here.

**Comment by valentinz** [comment]
This is finished. The solution is to start the server on port 8080 (default) and the web-client on port 8000 (default). After that it is possible to run nginx with the following configuration:
```
server {
	# General server configuration

	location / {
		proxy_pass http://127.0.0.1:8000;
	}

	location /api {
		proxy_pass http://127.0.0.1:8080/;
	}
}
```

For development purpose this should be enough.
